steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039:${SHORT_SHA}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039:${SHORT_SHA}"
