steps:
  # Step to build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-image:${SHORT_SHA}"
      - "."  # Ensure the build context is the root of the repository where the Dockerfile is located.

  # Step to push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-image:${SHORT_SHA}"

  # Step to deploy the image to Cloud Run
  - name: "google/cloud-sdk"
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "my-cloud-run-service"
      - "--image"
      - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-image:${SHORT_SHA}"
      - "--port"
      - "8080"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-image:${SHORT_SHA}"