steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_ARTIFACT_REGISTRY}/${_REPO_NAME}:${SHORT_SHA}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_ARTIFACT_REGISTRY}/${_REPO_NAME}:${SHORT_SHA}"

options:
  logging: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _ARTIFACT_REGISTRY: "us-central1-docker.pkg.dev/delarosa-cloud/harlan-100935039"
  _REPO_NAME: "my-app"

images:
  - "${_ARTIFACT_REGISTRY}/${_REPO_NAME}:${SHORT_SHA}"
