steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-app:$COMMIT_SHA',
      '.'
    ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-app:$COMMIT_SHA'
    ]

images:
  - 'us-central1-docker.pkg.dev/robust-catalyst-450803-e4/harlan-100935039/my-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
